### ISSUE TITLE
Running R from html

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/cpp-526-fall-2020#2]
Not an issue, more of a question. 

On the [first set of readings for week 1](http://ds4ps.org/dp4ss-textbook/ch-033-calculator.html), the page allows you to run R code on the page itself. Is this written into the markdown file? Or, is this a separate language that is being called by the page?

**Comment by lecy** [comment]
It's a plugin for RMD available through DataCamp: 

http://ds4ps.org/datacamp-light-demo-for-rmd/

Really nice for simple demos. A little more tricky if you need to use specific packages or import data. The widget basically sends code to a DataCamp server, which executes it and sends back results. So there are some limits.

**Comment by jacobtnyoung** [comment]
Oh ok. Cool.

I have seen this on a lot of sites and didn’t realize it is just in the markdown. Can you get any more awesome R?

**Comment by lecy** [comment]
Agreed!

They have been working hard to integrate a lot of tools into a coherent development environment. 

You can do a LOT in the R ecosystem now without having to learn a dozen more programming languages and frameworks. 

It has completely changed the calculus of the question, "should I learn R or some other language" since there are so many things you can do with R now other than just run regressions.
